// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDURGa6-clsMOY2vmo2IYUz_GWmY3rH2nE',
    appId: '1:1032795485650:web:f1bf942a5b4f10e8fbc40b',
    messagingSenderId: '1032795485650',
    projectId: 'instagram-clone-app-8ff39',
    authDomain: 'instagram-clone-app-8ff39.firebaseapp.com',
    storageBucket: 'instagram-clone-app-8ff39.appspot.com',
    measurementId: 'G-H7BVW81K4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1PVfvtkoFF67YnNNSvv7YoIYjmoKQOYI',
    appId: '1:1032795485650:android:6b76c2e8da740cf1fbc40b',
    messagingSenderId: '1032795485650',
    projectId: 'instagram-clone-app-8ff39',
    storageBucket: 'instagram-clone-app-8ff39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6rO8V1euHrNRbCnFQtcPJ8Pkp3Sbtw7A',
    appId: '1:1032795485650:ios:e8ce14f93e7a7ac8fbc40b',
    messagingSenderId: '1032795485650',
    projectId: 'instagram-clone-app-8ff39',
    storageBucket: 'instagram-clone-app-8ff39.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
